config/routes.rb
ProjTicketsysRefactored::Application.routes.draw do
  
  put 'service_area_forms/:id/move_up', :to => 'service_area_forms#move_up', :as => 'move_up'
  put 'service_area_forms/:id/move_down', :to => 'service_area_forms#move_down', :as => 'move_down'
  post 'service_area_forms/:id/set_providers', :to => 'service_area_forms#set_providers', :as => 'set_providers'
  delete 'service_area_forms/remove_field/:id', :to => 'service_area_forms#remove_field', :as => 'remove_field'  
  post 'service_area_forms/:id/create_field', :to => 'service_area_forms#create_field', :as => 'create_form_field'
  get 'service_area_forms/:id/new_field', :to => 'service_area_forms#new_field', :as => 'new_form_field'  
  
  
  get 'tickets/search', :as => 'search'
  get 'tickets/new_ticket', :to => 'tickets#new_ticket', :as => 'continue_new_ticket'
  get 'tickets/my_tickets', :as => 'my_tickets'
  put 'tickets/:id/set_primary_provider', :to => 'tickets#set_primary_provider',:as => 'set_primary_provider'
  put 'tickets/:id/add_additional_user', :to => 'tickets#add_user',:as => 'add_additional_user'
  put 'tickets/:id/add_additional_provider', :to => 'tickets#add_provider',:as => 'add_additional_provider'
  delete 'tickets/:id/remove_additional_user', :to => 'tickets#remove_user',:as => 'remove_additional_user'  
  delete 'tickets/:id/remove_additional_provider', :to => 'tickets#remove_provider',:as => 'remove_additional_provider'  
  put 'tickets/:id/close', :to => 'tickets#close', :as => 'close_ticket'
  put 'tickets/:id/open', :to => 'tickets#open', :as => 'open_ticket'
  
  put 'users/:id/change_password', :to => 'users#change_password', :as => 'change_password'
  post 'users/user_signup', :to => 'users#user_signup', :as => 'user_signup'
  put 'users/:id/verify', :to => 'users#verify', :as => 'verify_user'
  get 'users/:id/unverified_user', :to => 'users#unverified_user', :as => 'unverified_user'
  put 'users/:id/deactivate', :to => 'users#deactivate', :as => 'deactivate_user'
  put 'users/:id/reactivate', :to => 'users#reactivate', :as => 'reactivate_user'  
  
  put 'locations/:id/deactivate', :to => 'locations#deactivate', :as => 'deactivate_location'
  put 'locations/:id/reactivate', :to => 'locations#reactivate', :as => 'reactivate_location'
  
  put 'service_areas/:id/deactivate', :to => 'service_areas#deactivate', :as => 'deactivate_service_area'
  put 'service_areas/:id/reactivate', :to => 'service_areas#reactivate', :as => 'reactivate_service_area'
  
  resources :service_areas, :except => [:new, :show]
  resources :locations, :except => [:new, :show]
  resources :service_area_forms
  resources :tickets
  resources :users
  resources :notes, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "settings/index", :as => 'settings'
  
  get 'signin', :to => 'sessions#new', :as => 'signin'
  delete 'signout', :to => 'sessions#destroy', :as => 'signout'
  root :to  => 'sessions#new'
  
  
  
  

end

app/models/service_area.rb
class ServiceArea < ActiveRecord::Base
  # name:string
  # description:text
  # active:boolean
  
  scope :active, where(:active => true)
  scope :inactive, where(:active => false)
  
  has_many :tickets
  has_many :user_service_areas
  has_many :users, :through => :user_service_areas, :uniq => true
  
  validates :name, :presence => true, :uniqueness => true
  
  def inactive?
    active == false
  end
  
end

app/models/service_area_form.rb
class ServiceAreaForm < ActiveRecord::Base
  # default_provider_id:integer
  # service_area_id:integer
  # title:string
  
  belongs_to :service_area
  belongs_to :default_provider, :class_name => "User"
  has_many :fields, :foreign_key => "form_id", :dependent => :destroy, :order => 'position ASC'
  has_many :rules, :foreign_key => "form_id", :dependent => :destroy, :uniq => true
  
  
  class HHelper
    include Singleton
    include ActionView::Helpers::FormHelper
    #include ActionView::Helpers::UrlHelper
    #include ActionView::Helpers::TagHelper
    #include ActionView::Helpers::FormTagHelper
    #include ActionView::Helpers::AssetTagHelper
    #include ActionView::Helpers::FormOptionsHelper
  end
  
  def get_helper
    HHelper.instance
  end
  
  def get_form_engine
    all_fields = ""    
    if !fields.empty?
      fields.each do |f|
        all_fields += f.render
      end
    end
    Haml::Engine.new(all_fields)
  end
  
  def get_all
    all_fields = ""    
    if !fields.empty?
      fields.each do |f|
        all_fields += f.render
      end
    end
   all_fields
  end
  
  def get_select_options
    options = {}
    fields.each do |f|
      if f.select?
        key = "options_#{f.id}".to_sym
        options[key] = f.options
      end
    end
    options
  end
  
  def move_up(field)
    if field.position != 1
      other_field = fields.where(:position => field.position-1).first
      field.position -= 1
      other_field.position += 1
      field.save and other_field.save
    end    
  end
  
  def move_down(field)
    if field.position != fields.count
      other_field = fields.where(:position => field.position+1).first
      field.position += 1
      other_field.position -= 1
      field.save and other_field.save
    end
  end
  
  def update_field_order(del_pos)
    update_fields = fields.where("position > ?", del_pos)
    update_fields.each do |f|
      f.position -= 1
      f.save
    end
  end
  
end

app/controllers/service_areas_controller.rb
class ServiceAreasController < ApplicationController
  
  before_filter :check_if_signed_in
  before_filter :check_if_admin
  
  def destroy
    @service_areas = ServiceArea.find_by_id(params[:id])
    @service_areas.destroy
    flash[:notice] = "Service Area Was Deleted"
    redirect_to service_areas_path
  end  
  
  def index
     @service_areas = ServiceArea.all
  end  
  
  def create
    puts "here -----------------------------------"
    puts params[:service_area]
    @service_area = ServiceArea.new(params[:service_area])
    @service_area.active = true
    
    if @service_area.name.blank?
      @service_area.destroy
      flash[:error] = "A Service Area Must Have A Name"
      redirect_to service_areas_path
    elsif @service_area.save
      flash[:notice] = "New Service Area Added"
      redirect_to service_areas_path
    else
      @service_area.destroy
      flash[:error] = "A Service Area With That Name Already Exists"
      redirect_to service_areas_path
    end    
    
  end
  
  def edit
    @service_area = ServiceArea.find_by_id params[:id]
    puts "here I am"
    if !@service_area
      flash[:error] = "That Service Area Does Not Exist"
      redirect_to service_areas_path
    end    
  end
  
  
  def update
    service_area = ServiceArea.find_by_id(params[:id])
    service_area.update_attributes(params[:service_area])
    
    if service_area.save
      flash[:notice] = "Service Area Updated"      
    else
      flash[:notice] = "Service Area Could Not Be Updated"    
    end
    redirect_to service_areas_path
  end
  
  
  def deactivate
    service_area = ServiceArea.find_by_id(params[:id])    
    if !service_area
      flash[:error] = "That Service Area Does Not Exist"
      redirect_to service_areas_path and return
    end
    
    if service_area.inactive?
      flash[:error] = "That Service Area Was Already Deactivated"
      redirect_to service_areas_path and return
    end
    
    service_area.active = false
    service_area.save
    flash[:notice] = "Service Area Deactivated"
    redirect_to service_areas_path
  end
  
  def reactivate
    service_area = ServiceArea.find_by_id(params[:id])
    
    if !service_area
      flash[:error] = "That Service Area Does Not Exist"
      redirect_to service_areas_path and return
    end
    
    if service_area.active?
      flash[:error] = "That Service Area Is Currently Active"
      redirect_to service_areas_path and return
    end
    
    service_area.active = true
    service_area.save
    flash[:notice] = "Service Area Reactivated"
    redirect_to service_areas_path
  end
  
end

app/helpers/service_areas_helper.rb
module ServiceAreasHelper
end

app/views/service_areas/_service_area.html.haml
%tbody
  %tr{:class=>cycle("even","odd")}
    %td= service_area.name
    %td= service_area.description
    %td
      - if service_area.active?
        Yes
      - else
        No
    %td
      - if service_area.active? and current_user.admin?
        = button_to "Edit", edit_service_area_path(service_area), :method => :get
    %td
      - if current_user.admin?
        - if service_area.active?
          = button_to "Deactivate", deactivate_service_area_path(service_area), |
                                    :method => :put , :confirm => "Are you sure?"
        - else
          = button_to "Reactivate", reactivate_service_area_path(service_area), |
                                    :method => :put , :confirm => "Are you sure?"

app/views/service_areas/_service_area_form_fields.html.haml
.field
  %b= label :service_area, :name, "Name: "
  = text_field :service_area, :name, {:size=>"18"}
.field
  %b= label :service_area, :description, "Description:"
  %br
  #description-box= text_area :service_area, :description, {:size=>"30x5"}

app/views/service_areas/_service_area_header.html.haml
%thead
  %tr
    %th Name
    %th Description
    %th Active
    %th
    - if current_user.admin?
      %th

app/views/service_areas/edit.html.haml
%div{:align => "center"}
  #new-service-area.boxed-up
    -#= button_to 'Delete Service Area (Debug Only)', @service_area, :method => :delete
    = form_tag service_area_path(@service_area), :method => :put do
      = render "service_area_form_fields"
      .actions
        = submit_tag "Update Service Area"
%br

app/views/service_areas/index.html.haml
%h4 Add New Service Area
#new-service-area.boxed-up
  = form_tag service_areas_path, :method => :post do
    = render "service_area_form_fields"
    .actions
      = submit_tag "Create Service Area"
%h4 All Service Areas
%Table{:border=> "1", :cellpadding=>"1", :cellspacing=>"1", :width=>"99%", :overflow => "hidden" }
  = render "service_area_header"
  = render @service_areas
  