config/routes.rb
ProjTicketsysRefactored::Application.routes.draw do
  
  put 'service_area_forms/:id/move_up', :to => 'service_area_forms#move_up', :as => 'move_up'
  put 'service_area_forms/:id/move_down', :to => 'service_area_forms#move_down', :as => 'move_down'
  post 'service_area_forms/:id/set_providers', :to => 'service_area_forms#set_providers', :as => 'set_providers'
  delete 'service_area_forms/remove_field/:id', :to => 'service_area_forms#remove_field', :as => 'remove_field'  
  post 'service_area_forms/:id/create_field', :to => 'service_area_forms#create_field', :as => 'create_form_field'
  get 'service_area_forms/:id/new_field', :to => 'service_area_forms#new_field', :as => 'new_form_field'  
  
  
  get 'tickets/search', :as => 'search'
  get 'tickets/new_ticket', :to => 'tickets#new_ticket', :as => 'continue_new_ticket'
  get 'tickets/my_tickets', :as => 'my_tickets'
  put 'tickets/:id/set_primary_provider', :to => 'tickets#set_primary_provider',:as => 'set_primary_provider'
  put 'tickets/:id/add_additional_user', :to => 'tickets#add_user',:as => 'add_additional_user'
  put 'tickets/:id/add_additional_provider', :to => 'tickets#add_provider',:as => 'add_additional_provider'
  delete 'tickets/:id/remove_additional_user', :to => 'tickets#remove_user',:as => 'remove_additional_user'  
  delete 'tickets/:id/remove_additional_provider', :to => 'tickets#remove_provider',:as => 'remove_additional_provider'  
  put 'tickets/:id/close', :to => 'tickets#close', :as => 'close_ticket'
  put 'tickets/:id/open', :to => 'tickets#open', :as => 'open_ticket'
  
  put 'users/:id/change_password', :to => 'users#change_password', :as => 'change_password'
  post 'users/user_signup', :to => 'users#user_signup', :as => 'user_signup'
  put 'users/:id/verify', :to => 'users#verify', :as => 'verify_user'
  get 'users/:id/unverified_user', :to => 'users#unverified_user', :as => 'unverified_user'
  put 'users/:id/deactivate', :to => 'users#deactivate', :as => 'deactivate_user'
  put 'users/:id/reactivate', :to => 'users#reactivate', :as => 'reactivate_user'  
  
  put 'locations/:id/deactivate', :to => 'locations#deactivate', :as => 'deactivate_location'
  put 'locations/:id/reactivate', :to => 'locations#reactivate', :as => 'reactivate_location'
  
  put 'service_areas/:id/deactivate', :to => 'service_areas#deactivate', :as => 'deactivate_service_area'
  put 'service_areas/:id/reactivate', :to => 'service_areas#reactivate', :as => 'reactivate_service_area'
  
  resources :service_areas, :except => [:new, :show]
  resources :locations, :except => [:new, :show]
  resources :service_area_forms
  resources :tickets
  resources :users
  resources :notes, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "settings/index", :as => 'settings'
  
  get 'signin', :to => 'sessions#new', :as => 'signin'
  delete 'signout', :to => 'sessions#destroy', :as => 'signout'
  root :to  => 'sessions#new'
  
  
  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # name:string
  # email:string
  # privilege:string  
  # active:boolean
  # encrypted_password:string
  # salt:string
  # first_name:string
  # last_name:string
  
  
  default_scope :order => 'last_name ASC'
  scope :active, where(:active => true)
  scope :inactive, where(:active => false)
  
  has_many :user_tickets
  has_many :tickets, :through => :user_tickets, :uniq => true
  has_many :user_service_areas
  has_many :service_areas, :through => :user_service_areas, :uniq => true
  
  #validates :name, :uniqueness => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :encrypted_password, :presence => true
  validates :salt, :presence => true
  validates :privilege, :presence => true
  validates :email, :presence => true #, :uniqueness => true
  validates_inclusion_of :privilege, :in => ["user", "service provider", "admin"]
  
  # At some point privilege should be removed from this.
  # That will require changing how we create and update users.
  attr_accessible :email, :privilege, :first_name, :last_name, :name
  
  def admin?
    privilege == "admin"
  end  
  
  def service_provider?
    privilege == "service provider"
  end
  
  def provider?
    privilege == "service provider"
  end
  
  def user?
    privilege == "user"
  end  
  
  def inactive?
    active == false
  end
  
  def status   
    if !verified?
      "unverified"
    elsif inactive?
      "inactive"
    else
      "active"
    end
  end
  
  def service_areas_to_s
    
    if service_areas.blank?
      return "None"
    end
    
    str = ""
    service_areas.each do |sa|
      if sa.inactive?
        str += "#{sa.name}(Deactivated), "
      else
        str +="#{sa.name}, "
      end
    end
    str[0..-3]
  end
  
  def full_name
    first_name + " " + last_name
  end
  
  def last_first
    last_name + ", " + first_name
  end
  
  def last_first_initial
    last_name + ", " + first_name[0]
  end  
  
  def first_initial_last
    first_name[0] + ". " + last_name
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email email
    if !user
      return nil
    end
    
    if user.has_password?(submitted_password)
      return user
    end
  end
  
  def self.authenticate_with_salt(id, salt)
    user = User.find_by_id id
    if user and user.salt == salt
      user
    else
      nil
    end
  end
  
  def list_service_areas
    list_sa = ""  
    self.service_areas.each do |sa|
      list_sa += sa.name + " "
    end
    list_sa
  end
  
  def add_service_area_by_id(id)
    sa = self.user_service_areas.find_by_service_area_id(id)    
    if sa.nil?
      user_service_areas.build(:service_area_id => id)    
    end
  end
  
  def remove_service_area_by_id(id)
    sa = self.user_service_areas.find_by_service_area_id(id)    
    if sa
      sa.destroy
    end
  end
  
  def service_area_ids
    service_areas.collect do |sa|
      sa.id
    end
  end
  
  def service_area_ids_to_s
    all_sa = service_areas.collect do |sa|
      sa.id
    end
    get_str(all_sa)
  end
  
  def accessible_tickets
    if admin?
      Ticket.scoped
    elsif service_provider?
      if service_areas.blank?
        tickets.uniq
      else        
        sa_ids = service_area_ids_to_s
        Ticket.joins(:user_tickets).where("user_tickets.user_id = ? OR service_area_id IN  #{sa_ids}", self.id).uniq 
      end
    else
      tickets.uniq
    end
  end
  
  def has_password?(password)
    encrypted_password == encrypt(password)
  end
  
  
 
 
  def set_encrypted_password(password)
    self.salt = make_salt(password) if new_record?
    self.encrypted_password = encrypt(password)
  end
  
  private
  
  def encrypt(password)
    secure_hash("#{salt}--#{password}")
  end
  
  def make_salt(password)
    secure_hash("#{Time.now.utc}--#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
  
  def get_str(list)
    s = list.to_s
    s = s.sub("[","(")
    s = s.sub("]",")")
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :check_if_signed_in, :except => [:unverified_user, :user_signup]
  before_filter :check_if_admin, :only => [:new, :create, :destroy]
  before_filter :check_if_admin_or_self, :only => [:edit, :update]
  before_filter :check_if_admin_or_accessible, :only => [:index, :show]
  
  def new
    @user = User.new
    @service_areas = ServiceArea.all
    if session[:new_user]
      @first_name = session[:new_user][0]
      @last_name = session[:new_user][1]
      @email = session[:new_user][2]
      session[:new_user] = nil
    end
  end

  def create
    user = params[:user]
    
    if !user
      flash[:error] = "New User Could Not Be Created"
      redirect_to new_user_path and return
    end
    
    @first_name = user[:first_name]
    @last_name = user[:last_name]
    @email = user[:email]
    
    password = params[:password]
    
    if @first_name.blank?
      flash[:error] = "Please Enter A First Name."
      session[:new_user] = [@first_name, @last_name, @email]
      redirect_to new_user_path and return
    end
    
    if @last_name.blank?
      flash[:error] = "Please Enter A Last Name."
      session[:new_user] = [@first_name, @last_name, @email]
      redirect_to new_user_path and return
    end
    
    if !valid_email? @email
      flash[:error] = "That Is Not A Valid Email."
      session[:new_user] = [@first_name, @last_name, nil]
      redirect_to new_user_path and return
      @email = nil
    end
    
    if User.find_by_email @email
      flash[:error] = "A User With That Email Already Exists."
      session[:new_user] = [@first_name, @last_name, nil]
      redirect_to new_user_path and return
    end
    

    if !valid_password? password
      flash[:error] = "Password Must Be At Least 6 Characters Long"
      session[:new_user] = [@first_name, @last_name, @email]
      redirect_to new_user_path and return
    end
    
    if password != params[:password_confirmation]     
      flash[:error] = "Passwords Do Not Match"
      session[:new_user] = [@first_name, @last_name, @email]
      redirect_to new_user_path and return
    end
        
    @user = User.new()
    @user.first_name = @first_name
    @user.last_name = @last_name
    @user.email = @email
    @user.set_encrypted_password password
    @user.privilege = params[:user][:privilege]
    @user.active = true
    @user.verified = true
   
    service_areas = params[:service_area]
    if service_areas
      service_areas.each do |sa_id, checked|
        if checked == "1"        
          @user.add_service_area_by_id sa_id      
        end
      end
    end
    
    if @user.save
      flash[:notice] = "New User Created"
      redirect_to user_path @user
    else
      @user.destroy
      flash[:error] = "User Could Not Be Created!"
      redirect_to new_user_path
    end      
  end
  
  def unverified_user
    @user = User.find_by_id params[:id]
    if !@user
      flash[:error] = "User Does Not Exist"
      redirect_to signin_path and return
    end
    if @user.verified?   
      redirect_to tickets_path and return
    end
  end
  
  def verify
    user = User.find_by_id(params[:id])
    
    if !user
      flash[:error] = "That user does not exist"
      redirect_to users_path and return
    end
    
    if user.verified?
      flash[:error] = "That User Has Already Been Verified"
      redirect_to user and return
    end
    
    user.active = true
    user.verified = true
    user.save
    flash[:notice] = "User Verified"
    redirect_to user
  end
  
  def user_signup
    user = params[:user]
    if !user
      flash[:error] = "New Account could not be created!"
      redirect_to signin_path and return
    end
    
    @first_name = user[:first_name]
    @last_name = user[:last_name]
    @email = user[:email]
    
    password = user[:password]
    
    if @first_name.blank?
      flash[:error] = "Please Enter A First Name."
      session[:user_signup] = [@first_name, @last_name, @email]
      redirect_to signin_path and return
    end
    
    if @last_name.blank?
      flash[:error] = "Please Enter A Last Name."
      session[:user_signup] = [@first_name, @last_name, @email]
      redirect_to signin_path and return
    end
    
    if !valid_email? @email
      flash[:error] = "That Is Not A Valid Email."
      session[:user_signup] = [@first_name, @last_name, nil]
      redirect_to signin_path and return
      @email = nil
    end
    
    if User.find_by_email @email
      flash[:error] = "A User With That Email Already Exists."
      session[:user_signup] = [@first_name, @last_name, nil]
      redirect_to signin_path and return
    end
    
    if !valid_password? password
      flash[:error] = "Password Must Be At Least 6 Characters Long"
      session[:user_signup] = [@first_name, @last_name, @email]
      redirect_to signin_path and return
    end
    
    if password != user[:password_confirmation]     
      flash[:error] = "Passwords Do Not Match"
      session[:user_signup] = [@first_name, @last_name, @email]
      redirect_to signin_path and return
    end
        
    @user = User.new()
    @user.first_name = @first_name
    @user.last_name = @last_name
    @user.email = @email
    @user.set_encrypted_password password
    @user.privilege = "user"
    @user.active = false
    @user.verified = false
    
    if !@user.save
      flash[:error] = "New Account Could Not Be Created"
      redirect_to signin_path and return
    else
      redirect_to unverified_user_path @user
    end
    
  end
  
  def change_password
    @user = User.find_by_id(params[:id])
    
    if !@user
      flash[:error] = "That User Does Not Exist"
      redirect_to users_path and return
    end
    
    password = params[:password]
  
    if !valid_password? password
      flash[:error] = "Password Must Be At Least 6 Characters Long"      
      redirect_to edit_user_path @user and return
    end
    
    if password != params[:password_confirmation]     
      flash[:error] = "Passwords Do Not Match"      
      redirect_to edit_user_path @user and return
    end
    
    @user.set_encrypted_password password
    
    if !@user.save
      flash[:error] = "Password Could Not Be Changed"
      redirect_to edit_user_path @user and return
    else
      flash[:notice] = "Password Changed"
      redirect_to @user
    end
    
  end
  
  

  def update
    @user = User.find_by_id(params[:id])
    
    user = params[:user]
    
    if !user
      flash[:error] = "Something Went Wrong"
      redirect_to users_path and return
    end
    
    if !@user
      flash[:error] = "That User Does Not Exist"
      redirect_to users_path and return
    end   
    
    @first_name = user[:first_name]
    @last_name = user[:last_name]
    @email = user[:email]    
    puts "------------------------"
    puts @email
    if @first_name.blank?
      flash[:error] = "First Name Can Not Be Blank"
      redirect_to edit_user_path @user and return
    end
    
    if @last_name.blank?
      flash[:error] = "Last Name Can Not Be Blank."
      session[:user_signup] = [@first_name, @last_name, @email]
      redirect_to edit_user_path @user and return
    end
    
    if !valid_email? @email
      flash[:error] = "That Is Not A Valid Email."      
      redirect_to edit_user_path @user and return
    end
    
    if User.find_by_email @email and @email != @user.email
      flash[:error] = "A User With That Email Already Exists."      
      redirect_to edit_user_path @user and return
    end
    @user.first_name = @first_name
    @user.last_name = @last_name
    @user.email = @email
    
    service_areas = params[:service_area]
    
    if service_areas
      service_areas.each do |sa_id, checked|
        if checked == "1"        
          @user.add_service_area_by_id sa_id
        else        
          @user.remove_service_area_by_id sa_id
        end
      end
    end
    
    if @user.save
      flash[:notice] = "User Profile Updated"  
    else
      flash[:error] = "User Profile Could Not Be Updated"      
    end 
    redirect_to @user
  end

  def edit
    @user = User.find_by_id(params[:id])
    if !@user
      flash[:error] = "That User Does Not Exist"
      redirect_to users_path and return
    end
    @first_name = @user.first_name
    @last_name = @user.last_name
    @email = @user.email
    @service_areas = ServiceArea.active
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    flash[:notice] = "User Was Deleted"
    redirect_to users_path
  end
  
  def deactivate
    user = User.find_by_id(params[:id])
    
    if !user
      flash[:error] = "That User Does Not Exist"
      redirect_to users_path and return
    end
    
    if user.inactive?
      flash[:error] = "That User Was Already Deactivated"
      redirect_to users_path and return
    end
    
    user.active = false
    user.save
    flash[:notice] = "User Deactivated"
    redirect_to users_path
  end
  
  def reactivate
    user = User.find_by_id(params[:id])
    
    if !user
      flash[:error] = "That User Does Not Exist"
      redirect_to users_path and return
    end
    
    if user.active?
      flash[:error] = "That User Is Currently Active"
      redirect_to user and return
    end
    
    user.active = true
    user.save
    flash[:notice] = "User Reactivated"
    redirect_to user
  end

  def index
    @users = User.all
  end

  def show    
    @user = User.find_by_id(params[:id])    
    if !@user
      flash[:error] = "That User Does Not Exist"
      redirect_to users_path and return
    end  
    @service_areas = @user.service_areas_to_s 
  end  
  
end

app/helpers/users_helper.rb
module UsersHelper
  def valid_email?(email)
    #email =~ /[A-Z0-9._%-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/
    email.length > 0
  end
  
  def valid_password?(password)
    !password.blank? and password.length > 5   
  end
    
end

app/views/users/_password_fields.html.haml
%tr
  %td.right-just
    %b= label_tag :password, "Password:"
  %td= password_field_tag :password
%tr
  %td.right-just
    %b= label_tag :password_confirmation, "Confirm:"
  %td= password_field_tag :password_confirmation

app/views/users/_password_form.html.haml
-#- if (@user == current_user and current_page?(edit_user_path)) or current_page?(new_user_path)
-#  = form_tag change_password_path @user, :method => :put do.field
= form_tag change_password_path(@user), :method => :put do
  %table
    = render "password_fields"
    %tr
      %td
      %td= submit_tag "Change Password"
-#    .field
-#      = submit_tag "Change Password"

app/views/users/_service_area_fields.html.haml
.select
  - if !@service_areas.blank?
    %tr
      %td.vert-align
        %b.right-just= "Service Provider in:"
      %td
        - @service_areas.each do |sa|
          - if @user.service_areas.include? sa
            = check_box(:service_area, sa.id, :checked => true)
          - else
            = check_box(:service_area, sa.id)
          = label :service_area, :id, "#{sa.name}"
          %br

app/views/users/_user.html.haml
%tr{:class=>cycle("even","odd")}
  %td{:class => user.status}= link_to "#{user.last_first}", user
  %td{:class => user.status}= user.email
  %td{:class => user.status}= user.service_areas_to_s    
  %td{:class => user.status}= user.privilege  
  %td{:class => user.status}
    - if user.active?
      Yes
    - else
      No

app/views/users/_user_form.html.haml
= form_tag user_path(@user), :method => :put do
  %table 
    = render "user_form_fields"   
    - if current_user.admin?
      = render "service_area_fields"
    %tr
      %td
      %td= submit_tag "Update User"

app/views/users/_user_form_fields.html.haml
%tr
  %td.right-just
    %b= label :user, :first_name, "First Name:"
  %td= text_field :user, :first_name, :value => @first_name
%tr
  %td.right-just
    %b= label :user, :last_name, "Last Name:"
  %td= text_field :user, :last_name, :value => @last_name
%tr
  %td.right-just
    %b= label :user, :email, "Email:"
  %td= text_field :user, :email, :value => @email
- if current_user.admin?
  %tr
    %td.right-just
      %b= label :user, :privilege, "Privileges:"
    %td= select :user, :privilege, get_privileges

app/views/users/_user_header.html.haml
%thead
  %tr
    %th Name
    %th Email
    %th Service Areas
    %th Privilege
    %th Active

app/views/users/_user_menu.html.haml
%table
  %tr
    %td
      - if @user.active? and @user.verified?
        = button_to 'Edit User', edit_user_path(@user), :method => :get
    %td
      - if current_user.admin? and @user.verified?
        - if @user.active?
          = button_to "Deactivate User", deactivate_user_path, :method => :put , |
                                        :confirm => "Are you sure you want to deactivate this user?"
        - else
          = button_to "Reactivate User", reactivate_user_path, :method => :put , |
                                        :confirm => "Are you sure you want to reactivate this user?"
    -#%td
      -#= button_to 'Delete User (Debug Only)', @user, :method => :delete
    %td
      -if !@user.verified?
        = button_to "Verify User", verify_user_path, :method => :put                           
%hr

app/views/users/edit.html.haml
%div{:align => "center"}
  #edit-user.boxed-up
    %h4= "Edit User"
    %table{:width => "850px"}
      %tr
        %td= render "user_form"        
        -#%td{:width => "30px"}
        %td.vert-align= render "password_form"
%br

app/views/users/index.html.haml
%div
  %h4= button_to "Create a new User", new_user_path, :method => :get
  %h4 All Users
  %center
    %Table{:border=> "1", :cellpadding=>"1", :cellspacing=>"1", :width=>"99%", :overflow=>"hidden" }
      = render "user_header"
      = render @users

app/views/users/new.html.haml
%div{:align => "center"}
  #new-user.boxed-up
    %h4= "Create New User"  
    %table
      = form_tag users_path, :method => :post do
        = render "user_form_fields"
        = render "service_area_fields"      
        = render "password_fields"
        %tr
          %td
          %td= submit_tag "Create User"
%br

app/views/users/show.html.haml
%div{:align => "center"}
  #show-user.boxed-up
    - if current_user.admin? or current_user.id == @user.id
      = render "user_menu"
    -if !@user.verified?
      %h4.red= "Unverified User"
    -elsif !@user.active?
      %h4.red= "Deactivated User"
    %ul 
    %table
      %tr
        %td.right-just
          %b= "Name: " 
        %td= @user.full_name
      %tr
        %td.right-just
          %b= "Email: "
        %td= @user.email
      %tr
        %td.right-just
          %b= "Active: "        
        -if @user.active?  
          %td= "Yes"
        -else
          %td= "No"
      %tr
        %td.right-just
          %b= "Verified: "
        -if @user.verified?
          %td= "Yes"
        -else
          %td= "No"
      %tr
        %td.right-just
          %b= "Privilege: "
        %td= @user.privilege
      %tr
        %td.right-just
          %b= "Service Areas: " 
        %td= "#{@service_areas}"
%br

app/views/users/unverified_user.html.haml
%div{:align => "center"}  
  %b.red= "Unverified Account - Your Account Is Still Under Review"
  %p
  #unverified-user.boxed-up
    %table
      %tr
        %td.right-just
          %b= "Name: " 
        %td= @user.full_name    
      %tr
        %td.right-just
          %b= "Email: "
        %td= @user.email
%br