config/routes.rb
ProjTicketsysRefactored::Application.routes.draw do
  
  put 'service_area_forms/:id/move_up', :to => 'service_area_forms#move_up', :as => 'move_up'
  put 'service_area_forms/:id/move_down', :to => 'service_area_forms#move_down', :as => 'move_down'
  post 'service_area_forms/:id/set_providers', :to => 'service_area_forms#set_providers', :as => 'set_providers'
  delete 'service_area_forms/remove_field/:id', :to => 'service_area_forms#remove_field', :as => 'remove_field'  
  post 'service_area_forms/:id/create_field', :to => 'service_area_forms#create_field', :as => 'create_form_field'
  get 'service_area_forms/:id/new_field', :to => 'service_area_forms#new_field', :as => 'new_form_field'  
  
  
  get 'tickets/search', :as => 'search'
  get 'tickets/new_ticket', :to => 'tickets#new_ticket', :as => 'continue_new_ticket'
  get 'tickets/my_tickets', :as => 'my_tickets'
  put 'tickets/:id/set_primary_provider', :to => 'tickets#set_primary_provider',:as => 'set_primary_provider'
  put 'tickets/:id/add_additional_user', :to => 'tickets#add_user',:as => 'add_additional_user'
  put 'tickets/:id/add_additional_provider', :to => 'tickets#add_provider',:as => 'add_additional_provider'
  delete 'tickets/:id/remove_additional_user', :to => 'tickets#remove_user',:as => 'remove_additional_user'  
  delete 'tickets/:id/remove_additional_provider', :to => 'tickets#remove_provider',:as => 'remove_additional_provider'  
  put 'tickets/:id/close', :to => 'tickets#close', :as => 'close_ticket'
  put 'tickets/:id/open', :to => 'tickets#open', :as => 'open_ticket'
  
  put 'users/:id/change_password', :to => 'users#change_password', :as => 'change_password'
  post 'users/user_signup', :to => 'users#user_signup', :as => 'user_signup'
  put 'users/:id/verify', :to => 'users#verify', :as => 'verify_user'
  get 'users/:id/unverified_user', :to => 'users#unverified_user', :as => 'unverified_user'
  put 'users/:id/deactivate', :to => 'users#deactivate', :as => 'deactivate_user'
  put 'users/:id/reactivate', :to => 'users#reactivate', :as => 'reactivate_user'  
  
  put 'locations/:id/deactivate', :to => 'locations#deactivate', :as => 'deactivate_location'
  put 'locations/:id/reactivate', :to => 'locations#reactivate', :as => 'reactivate_location'
  
  put 'service_areas/:id/deactivate', :to => 'service_areas#deactivate', :as => 'deactivate_service_area'
  put 'service_areas/:id/reactivate', :to => 'service_areas#reactivate', :as => 'reactivate_service_area'
  
  resources :service_areas, :except => [:new, :show]
  resources :locations, :except => [:new, :show]
  resources :service_area_forms
  resources :tickets
  resources :users
  resources :notes, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "settings/index", :as => 'settings'
  
  get 'signin', :to => 'sessions#new', :as => 'signin'
  delete 'signout', :to => 'sessions#destroy', :as => 'signout'
  root :to  => 'sessions#new'
  
  
  
  

end

app/views/shared/_menu_bar.html.haml
%ul
  - if current_user.admin?
    %li
      = link_to "Tickets", tickets_path    
    %li
      = link_to "New Ticket", new_ticket_path
    %li
      = link_to "Users", users_path
    %li
      = link_to "My Profile", current_user
    %li
      = link_to "Settings", settings_path
    %li
      %a{:href=>"javascript:toggle('tbl')"}= "Search"
  - elsif current_user.service_provider?
    %li
      = link_to "Tickets", tickets_path
    %li
      = link_to "New Ticket", new_ticket_path
    %li
      = link_to "My Profile", current_user
    %li
      = link_to "Settings", settings_path 
    %li      
      %a{:href=>"javascript:toggle('tbl')"}= "Search"     
  - elsif current_user.user?
    %li
      = link_to "Tickets", tickets_path
    %li
      = link_to "New Ticket", new_ticket_path
    %li
      = link_to "My Profile", current_user
    %li     
      %a{:href=>"javascript:toggle('tbl')"}= "Search"
  - else
    

app/views/shared/_search_bar.html.haml
:javascript
  function toggle(id) {
    var e = document.getElementById(id);
 
    if (e.style.display == '')
      e.style.display = 'none';
    else
      e.style.display = '';
  }
- if current_page?(search_path)
  %div{:id=>"tbl", :name=>"tbl"}
    = render "shared/search_fields"
-else
  %div{:id=>"tbl", :name=>"tbl", :style=>"overflow:hidden;display:none"}
    = render "shared/search_fields"
%br

app/views/shared/_search_fields.html.haml
%div{:align => "center"}
  #search-bar.boxed-up
    = form_tag search_path, :method => :get do
      %table#search-formatting
        %tr
          %td
            %table
              %tr
                %td
                  %b.show-inline= label_tag :ticket_id, "Ticket Number: "
                  = text_field_tag :ticket_id, @ticket_id, :size => "3"
                %td
                  %b.show-inline= label_tag :everything, "All Fields: "
                  = text_field_tag :everything, @everything
                - if !current_user.user?
                  %td= select_tag :all_mine, options_for_select(["My Tickets", "All Tickets"], selected = @all_mine) 
                %td= select_tag :open_closed, options_for_select(["Opened", "Closed", "Both"], selected = @type) 
                %td= select_tag :location_id, options_for_select(get_locations, selected = @location_id), :prompt => " -- Location -- "
                %td= submit_tag "Search", :class => "search-button"
        %tr
          %td= render "shared/search_service_areas"  
        %tr
          %td        
            %table
              %tr
                %td
                  %b= label_tag :opened_start_text, "Opened Between "
                  = text_field_tag :opened_start_text, @opened_start_text, :class => "date-text"
                %td
                  %b= label_tag :opened_end_text, " And "
                  = text_field_tag :opened_end_text, @opened_end_text, :class => "date-text"

app/views/shared/_search_service_areas.html.haml
- get_service_areas.each do |name, id|
  = check_box :service_areas, id, :checked => service_area_checked?(id)
  = label :service_areas, :id, "#{name}"
  .hide-me.show-inline= "x"

app/views/shared/_the_flash.html.haml
%div{:align => "center"}  
  - if !flash.empty?
    - flash.each do |key, value|
      %div{:class => key}= value
  - else
    %div{:class => "no-flash"}