config/routes.rb
ProjTicketsysRefactored::Application.routes.draw do
  
  put 'service_area_forms/:id/move_up', :to => 'service_area_forms#move_up', :as => 'move_up'
  put 'service_area_forms/:id/move_down', :to => 'service_area_forms#move_down', :as => 'move_down'
  post 'service_area_forms/:id/set_providers', :to => 'service_area_forms#set_providers', :as => 'set_providers'
  delete 'service_area_forms/remove_field/:id', :to => 'service_area_forms#remove_field', :as => 'remove_field'  
  post 'service_area_forms/:id/create_field', :to => 'service_area_forms#create_field', :as => 'create_form_field'
  get 'service_area_forms/:id/new_field', :to => 'service_area_forms#new_field', :as => 'new_form_field'  
  
  
  get 'tickets/search', :as => 'search'
  get 'tickets/new_ticket', :to => 'tickets#new_ticket', :as => 'continue_new_ticket'
  get 'tickets/my_tickets', :as => 'my_tickets'
  put 'tickets/:id/set_primary_provider', :to => 'tickets#set_primary_provider',:as => 'set_primary_provider'
  put 'tickets/:id/add_additional_user', :to => 'tickets#add_user',:as => 'add_additional_user'
  put 'tickets/:id/add_additional_provider', :to => 'tickets#add_provider',:as => 'add_additional_provider'
  delete 'tickets/:id/remove_additional_user', :to => 'tickets#remove_user',:as => 'remove_additional_user'  
  delete 'tickets/:id/remove_additional_provider', :to => 'tickets#remove_provider',:as => 'remove_additional_provider'  
  put 'tickets/:id/close', :to => 'tickets#close', :as => 'close_ticket'
  put 'tickets/:id/open', :to => 'tickets#open', :as => 'open_ticket'
  
  put 'users/:id/change_password', :to => 'users#change_password', :as => 'change_password'
  post 'users/user_signup', :to => 'users#user_signup', :as => 'user_signup'
  put 'users/:id/verify', :to => 'users#verify', :as => 'verify_user'
  get 'users/:id/unverified_user', :to => 'users#unverified_user', :as => 'unverified_user'
  put 'users/:id/deactivate', :to => 'users#deactivate', :as => 'deactivate_user'
  put 'users/:id/reactivate', :to => 'users#reactivate', :as => 'reactivate_user'  
  
  put 'locations/:id/deactivate', :to => 'locations#deactivate', :as => 'deactivate_location'
  put 'locations/:id/reactivate', :to => 'locations#reactivate', :as => 'reactivate_location'
  
  put 'service_areas/:id/deactivate', :to => 'service_areas#deactivate', :as => 'deactivate_service_area'
  put 'service_areas/:id/reactivate', :to => 'service_areas#reactivate', :as => 'reactivate_service_area'
  
  resources :service_areas, :except => [:new, :show]
  resources :locations, :except => [:new, :show]
  resources :service_area_forms
  resources :tickets
  resources :users
  resources :notes, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  
  get "settings/index", :as => 'settings'
  
  get 'signin', :to => 'sessions#new', :as => 'signin'
  delete 'signout', :to => 'sessions#destroy', :as => 'signout'
  root :to  => 'sessions#new'
  
  
  
  

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :check_if_signed_in
  before_filter :deny_user
  
  def index
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/index.html.haml
%div{:align => "center"}
  #settings.boxed-up
    %h4{:align => "center"}= "Settings"
    -if current_user.admin?
      %h4= link_to "Location Settings", locations_path
      %h4= link_to "Service Area Settings", service_areas_path    
    %h4= link_to "Service Area Forms", service_area_forms_path
%br

app/views/settings/locations.html.haml
%div
  %h4 Add a new Location
  %div
    = form_tag create_location_path, :method => :post do
      .field
        = label :location, :name, "Name: "
        = text_field :location, :name
      .actions
        = submit_tag "Create Location"
  %h4 All Locations
  %Table{:border=> "1", :cellpadding=>"1", :cellspacing=>"1", :width=>"100%", :overflow=>"hidden" }
    = render "locations/location_header"
    = render @locations

app/views/settings/service_areas.html.haml
%div
  %h4 Add a new Service Area
  %div
    = form_tag create_service_area_path, :method => :post do
      .field
        = label :service_area, :name, "Name: "
        = text_field :service_area, :name
      .actions
        = submit_tag "Create Service Area"
  %h4 All Service Areas
  %Table{:border=> "1", :cellpadding=>"1", :cellspacing=>"1", :width=>"100%", :overflow=>"hidden" }
    = render "service_areas/service_area_header"
    = render @service_areas